import { PresetFile } from "../types";

export const preset7: PresetFile = {
  id: "preset-7",
    title: "Nemu's Normal",
    description: "Nemu's optimization FastFlags. 😋",
    content: JSON.stringify(
      {
        "FLogNetwork": "7",
        "FFlagHandleAltEnterFullscreenManually": "False",
        "FStringDebugLuaLogPattern": "ExpChat/mountClientApp",
        "FStringDebugLuaLogLevel": "trace",
        "FFlagEnableInGameMenuChrome": "True",
        "DFFlagDisableDPIScale": "True",
        "FFlagEnableInGameMenuModernization": "True",
        "FIntFullscreenTitleBarTriggerDelayMillis": 3600000,
        "FIntRenderShadowIntensity": 0,
        "DFIntMaxFrameBufferSize": 10,
        "DFIntBufferCompressionLevel": 0,
        "DFIntBufferCompressionThreshold": 100,
        "DFIntPerformanceControlFrameTimeMax": 1,
        "DFIntPerformanceControlFrameTimeMaxUtility": -1,
        "FFlagPushFrameTimeToHarmony": "True",
        "DFIntAnimatorThrottleMaxFramesToSkip": 1,
        "DFIntNumFramesAllowedToBeAboveError": 1,
        "DFIntVisibilityCheckRayCastLimitPerFrame": 10,
        "DFIntNetworkSchemaCompressionRatio": 100,
        "DFIntTimeBetweenSendConnectionAttemptsMS": 200,
        "FFlagFastGPULightCulling3": "True",
        "FFlagDebugCheckRenderThreading": "True",
        "FFlagRenderDebugCheckThreading2": "True",
        "FFlagDebugGraphicsPreferD3D11": "True",
        "DFFlagDebugDisableTimeoutDisconnect": "True",
        "FFlagAlwaysShowVRToggleV3": "False",
        "FFlagDisableFeedbackSoothsayerCheck": "False",
        "DFIntVoiceChatVolumeThousandths": 8600,
        "DFFlagCollectAudioPluginTelemetry": "False",
        "DFFlagDebugPerfMode": "True",
        "DFFlagEmitSafetyTelemetryInCallbackEnable": "False",
        "DFFlagEnablePreloadAvatarAssets": "True",
        "DFFlagEnableSkipUpdatingGlobalTelemetryInfo2": "False",
        "DFFlagEnableSoundPreloading": "True",
        "DFFlagEnableTelemetryV2FRMStats": "False",
        "DFFlagEnableTexturePreloading": "True",
        "DFFlagGpuVsCpuBoundTelemetry": "False",
        "DFFlagGraphicsQualityUsageTelemetry": "False",
        "DFFlagPerformanceControlEnableMemoryProbing3": "True",
        "DFFlagRccLoadSoundLengthTelemetryEnabled": "False",
        "DFFlagReportAssetRequestV1Telemetry": "False",
        "DFFlagReportRenderDistanceTelemetry": "False",
        "DFFlagRobloxTelemetryAddDeviceRAM": "False",
        "DFFlagRobloxTelemetryAddDeviceRAMPointsV2": "False",
        "DFFlagSampleAndRefreshRakPing": "True",
        "DFFlagSimOptimizeSetSize": "True",
        "DFFlagTaskSchedulerAvoidSleep": "True",
        "DFFlagTeleportClientAssetPreloadingDoingExperiment": "True",
        "DFFlagTeleportClientAssetPreloadingDoingExperiment2": "True",
        "DFFlagTeleportClientAssetPreloadingEnabledIXP": "True",
        "DFFlagTeleportClientAssetPreloadingEnabledIXP2": "True",
        "DFIntAssetPreloading": 2147483647,
        "DFIntCanHideGuiGroupId": 32380007,
        "DFIntCharacterLoadTime": 1,
        "DFIntContentProviderPreloadHangTelemetryHundredthsPercentage": 0,
        "DFIntMemoryUtilityCurveBaseHundrethsPercent": 10000,
        "DFIntMemoryUtilityCurveNumSegments": 100,
        "DFIntMemoryUtilityCurveTotalMemoryReserve": 0,
        "DFIntNumAssetsMaxToPreload": 2147483647,
        "DFIntPreloadAvatarAssets": 2147483647,
        "DFIntS2PhysicsSenderRate": 128,
        "DFIntTeleportClientAssetPreloadingHundredthsPercentage": 100000,
        "DFIntTeleportClientAssetPreloadingHundredthsPercentage2": 100000,
        "DFIntTrackCountryRegionAPIHundredthsPercent": 10000,
        "FFlagAddDMLogging": "False",
        "FFlagAssetPreloadingIXP": "True",
        "FFlagBetaBadgeLearnMoreLinkFormview": "False",
        "FFlagChatTranslationEnableSystemMessage": "False",
        "FFlagContentProviderPreloadHangTelemetry": "False",
        "FFlagControlBetaBadgeWithGuac": "False",
        "FFlagDebugForceFSMCPULightCulling": "True",
        "FFlagEnablePartyVoiceOnlyForEligibleUsers": "False",
        "FFlagEnablePartyVoiceOnlyForUnfilteredThreads": "False",
        "FFlagEnablePreferredTextSizeGuiService": "True",
        "FFlagEnablePreferredTextSizeScale": "True",
        "FFlagEnablePreferredTextSizeSettingInMenus2": "True",
        "FFlagEnablePreferredTextSizeStyleFixesInAvatarExp": "True",
        "FFlagHighlightOutlinesOnMobile": "True",
        "FFlagImproveShiftLockTransition": "True",
        "FFlagLoginPageOptimizedPngs": "True",
        "FFlagLuauCodegen": "True",
        "FFlagMessageBusCallOptimization": "True",
        "FFlagPreloadAllFonts": "True",
        "FFlagPreloadTextureItemsOption4": "True",
        "FFlagQuaternionPoseCorrection": "True",
        "FFlagRenderCBRefactor2": "True",
        "FFlagRenderLegacyShadowsQualityRefactor": "True",
        "FFlagRenderSkipReadingShaderData": "False",
        "FFlagShoeSkipRenderMesh": "False",
        "FFlagUserBetterInertialScrolling": "True",
        "FFlagUserCameraControlLastInputTypeUpdate": "False",
        "FFlagUserShowGuiHideToggles": "True",
        "FFlagVideoServiceAddHardwareCodecMetrics": "True",
        "FFlagVoiceBetaBadge": "False",
        "FIntCLI20390_2": 0,
        "FIntCameraMaxZoomDistance": 2147483647,
        "FStringGetPlayerImageDefaultTimeout": "1",
        "FStringTencentAuthPath": "null",
        "FStringVoiceBetaBadgeLearnMoreLink": "null",
        "FFlagEnablePreferredTextSizeStyleFixesInAppShell4": "True"
    },
      null,
      2
    ),
    category: "performance",
    difficulty: "safe",
    compatibility: ["Roblox"],
    version: "1.1",
};
