import { PresetFile } from "../types";

export const preset8: PresetFile = {
  id: "preset-8",
    title: "Unterial",
    description: "Anti Data sharing, Better WiFi/FPS Optimization, Reduce Latency/Delay/Frames. (change ur hardware settings)",
    content: JSON.stringify(
      {
        "DFFlagPolicyServiceReportDetailIsNotSubjectToChinaPolicies": "False",
        "DFFlagUpdateBoundExtentsForHugeMixedReplicationComponents": "True",
        "DFFlagPolicyServiceReportIsNotSubjectToChinaPolicies": "False",
        "DFFlagSimAdaptiveExplicitlyMarkInterpolatedAssemblies": "True",
        "DFFlagSimAdaptiveAdjustTimestepForControllerManager": "False",
        "DFFlagAcceleratorUpdateOnPropsAndValueTimeChange": "True",
        "DFFlagOnlyDecrementCompletenessIfReplicating": "True",
        "DFFlagReportReplicatorStatsToTelemetryV22": "False",
        "DFFlagHttpTrackBandwidthBasedOnMsgSize": "False",
        "DFFlagCorrectServerReplicatorStatsIP": "False",
        "DFFlagRakNetTelemV2DownloadBwTracker": "False",
        "DFFlagReplicatorSeparateVarThresholds": "True",
        "DFFlagDebugDisableTelemetryAfterTest": "True",
        "DFFlagSimSmoothedRunningController2": "True",
        "DFFlagClampIncomingReplicationLag": "True",
        "DFFlagHumanoidReplicateSimulated2": "True",
        "DFFlagSolverStateReplicatedOnly2": "True",
        "DFFlagReplicateCreateToPlayer": "True",
        "DFFlagMergeFakeInputEvents4": "True",
    
        "DFIntPolicyServiceReportDetailIsNotSubjectToChinaPoliciesHundredthsPercentage": "0",
        "DFIntReportSimulationToFBLatencyInfluxHundredthsPercentage": "0",
        "DFIntServerBandwidthPlayerSampleRateFacsOverride": "2147465500",
        "DFIntServerRakNetBandwidthPlayerSampleRate": "2147465500",
        "DFIntReportNetworkSyncMemoryUsage2EveryXSeconds": "86400",
        "DFIntNetworkObjectStatsCollectorGlobalCapThrottleHP": "0",
        "DFIntBandwidthManagerDataSenderMaxWorkCatchupMs": "2000",
        "DFIntGraphicsOptimizationModeMinFrameTimeTargetMs": "10",
        "DFIntGraphicsOptimizationModeFRMFrameRateTarget": "480",
        "DFIntClusterSenderMaxUpdateBandwidthBps": "560000000",
        "DFIntMegaReplicatorNetworkQualityProcessorUnit": "10",
        "DFIntBandwidthManagerApplicationDefaultBps": "512000",
        "DFIntTimestepArbiterHumanoidLinearVelThreshold": "20",
        "DFIntServerBandwidthPlayerSampleRate": "2147465500",
        "DFIntClusterSenderMaxJoinBandwidthBps": "560000000",
        "DFIntSimExplicitlyCappedTimestepMultiplier": "500",
        "DFIntSimDefaultHumanoidTimestepMultiplier": "100",
        "DFIntTimestepArbiterCollidingHumanoidTsm": "100",
        "DFIntRakNetResendMinThresholdTimeInUs": "75000",
        "DFIntLatencyLoggingThresholdMs": "2147465500",
        "DFIntMaxProcessPacketsStepsPerCyclic": "150",
        "DFIntMaxDebugNetworkUpdateTimestamps": "0",
        "DFIntMaxProcessPacketsJobScaling": "300",
        "DFIntDebugDynamicRenderKiloPixels": "-1",
        "DFIntNetworkQualityResponderUnit": "10",
        "DFIntSendRakNetStatsInterval": "86400",
        "DFIntNetworkStreamMinGrowSize": "4096",
        "DFIntRakNetMinAckGrowthPercent": "50",
        "DFIntSignalRCoreRpcQueueSize": "256",
        "DFIntTaskSchedulerTargetFps": "3500",
        "DFIntNetworkStreamInitSize": "1024",
        "DFIntRakNetSelectTimeoutMs": "10",
        "DFIntS2PhysicsSenderRate": "240",
        "DFIntSignalRCoreTimerMs": "750",
        "DFIntRuntimeConcurrency": "23",
        "DFIntMaxFrameBufferSize": "4",
        "DFIntRakNetLoopMs": "1",
    
        "DFLogClientRecvFromRaknet": "False",
        "DFLogLargeReplicatorTrace": "False",
    
        "DFStringCrashUploadToBacktraceBaseUrl": "https://opt-out.roblox.com/",
        "DFStringHttpPointsReporterUrl": "https://opt-out.roblox.com/",
        "DFStringRobloxAnalyticsURL": "https://opt-out.roblox.com/",
        "DFStringTelemetryV2Url": "https://opt-out.roblox.com/",
    
        "FFlagPreComputeAcceleratorArrayForSharingTimeCurve": "True",
        "FFlagReportFRMGPUFrameTimeTelemetryInPerfdata": "False",
        "FFlagFFlagEnableAdDataPlayIntentEventIngest": "False",
        "FFlagFFlagEnableAdDataReferralEventIngest": "False",
        "FFlagSpecifyNetworkReplicatorScopeForItems": "True",
        "FFlagUserCameraControlLastInputTypeUpdate": "False",
        "FFlagEnableServiceInitBreakdownTelemetry": "False",
        "FFlagEnablePhysicsAdaptiveTimeSteppingIXP": "True",
        "FFlagKeyframeSequenceUseRuntimeSyncPrims": "True",
        "FFlagTaskSchedulerLimitTargetFpsTo2402": "False",
        "FFlagHandleAltEnterFullscreenManually": "False",
        "FFlagHumanoidStateUseRuntimeSyncPrims": "True",
        "FFlagAnimationCurveDenseCacheEnabled6": "True",
        "FFlagSpecifyNetworkReplicatorScope": "True",
        "FFlagStylingFasterTagProcessing": "True",
        "FFlagEnableTelemetryProtocol": "False",
        "FFlagEnableTelemetryService1": "False",
        "FFlagLuaMenuPerfImprovements": "True",
        "FFlagSimDcdDeltaReplication": "True",
        "FFlagSimDcdRefactorDelta3": "True",
        "FFlagSortKeyOptimization": "True",
        "FFlagFasterPreciseTime4": "True",
        "FFlagAdServiceEnabled": "False",
        "FFlagSmoothInputOffset": "True",
        "FFlagMovePrerenderV2": "False",
        "FFlagDebugDisplayFPS": "False",
        "FFlagMovePrerender": "False",
    
        "FIntMaxTimestepMultiplierAcceleration": "100",
        "FIntMaxTimestepMultiplierVelocity": "100",
        "FIntMaxTimestepMultiplierHumanoid": "100",
        "FIntTaskSchedulerAutoThreadLimit": "23",
        "FIntInterpolationMaxDelayMSec": "95",
        "FIntDefaultJitterN": "0",
        "FIntCLI20390_2": "1",
    
        "FLogTencentAuthPath": "Renshao",
    
        "FStringGameLaunchLinkURL": "(?:(?:https?://\w+\.roblox(?:labs)?\.com(?:/[A-Za-z]{2}(-[A-Za-z0-9]{2,3})?)?/games/start\?)|(?:roblox(?:mobile)?://(?:experiences/start\?)?))(?:(?:(?:(?:id=\d+)|(?:placeid=\d+)|(?:accessCode=(?:\w|\-)+)|(?:reservedServerAccessCode=(?:\w|\-)+)|(?:launchData=(?:.+))|(?:eventId=(?:\d+)/?",
        "FStringPhysicsAdaptiveTimeSteppingIXP": "Physics.DefaultTimeStepping",
        "FStringTencentAuthPath": " Renshao"
    },
      null,
      2
    ),
    category: "performance",
    difficulty: "experimental",
    compatibility: ["Roblox"],
    version: "3.0",
};
